packages:
  - "packages/*"
  - "apps/*"

catalogs:
  e2e:
    "@playwright/test": ^1.57.0

  react19:
    "@types/react": ^19.2.7
    "@types/react-dom": ^19.2.3
    react: ^19.2.2
    react-dom: ^19.2.2
